spring:
  #JWT
  jwt:
    secret: testestestestestestestestestestsetsetsetsetsetsetsetsetsetsetestt

  #OAUTH 2.0
  security:
    oauth2:
      client:
        registration:
          # ─────────── Naver ───────────
          naver:
            client-name: naver
            client-id: test_id
            client-secret: test
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email

          # ─────────── Google ───────────
          google:
            client-name: google
            client-id: test_id
            client-secret: test
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

          # ─────────── Kakao ───────────
          kakao:
            client-name: kakao
            client-id: test_id
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email

        provider:
          # ─────────── Naver ───────────
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          # ─────────── Kakao ───────────
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id