spring:
  application:
    name: Konnect

  config:
    import:
      - "classpath:application-secret.yml"
      - optional:file:.env.dev[.properties]

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

client:
  url: ${CLIENT_URL}